# Generated by Django 4.0.5 on 2022-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='rregister',
            name='location',
        ),
        migrations.AddField(
            model_name='rregister',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='blog.address'),
        ),
    ]
