# Generated by Django 4.0.5 on 2022-08-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_restaurant_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rregister',
            name='location',
            field=models.ManyToManyField(to='blog.address'),
        ),
    ]
