# Generated by Django 4.0.5 on 2022-08-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Active', max_length=20),
        ),
    ]
